# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05ed090c7e7c622d67ba023218060d5d2d033e7810f984197f9c04f0a6fe4ab51305ab5ce91fbef69eb89b3e9fa7005034e7f514f97c014eadddd787a4ce2689

test:
  secret_key_base: 6ee7b0633367eae236a146bc8892a90a5fa2644517fc743d8b2274b3992198eda0eaf6132bd53d0f43c3cd5b36e33b421a3a5efb221c51d29accf6bc0a86c127

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
